// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sborsh1kmusora/micro/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

type ItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemRepository) EXPECT() *ItemRepository_Expecter {
	return &ItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ItemRepository) Create(_a0 context.Context, _a1 *model.ItemInfo) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ItemInfo) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ItemInfo) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ItemInfo) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *model.ItemInfo
func (_e *ItemRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *ItemRepository_Create_Call {
	return &ItemRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *ItemRepository_Create_Call) Run(run func(_a0 context.Context, _a1 *model.ItemInfo)) *ItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.ItemInfo))
	})
	return _c
}

func (_c *ItemRepository_Create_Call) Return(_a0 string, _a1 error) *ItemRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_Create_Call) RunAndReturn(run func(context.Context, *model.ItemInfo) (string, error)) *ItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *ItemRepository) Get(_a0 context.Context, _a1 string) (*model.Item, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Item, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Item); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ItemRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ItemRepository_Expecter) Get(_a0 interface{}, _a1 interface{}) *ItemRepository_Get_Call {
	return &ItemRepository_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *ItemRepository_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *ItemRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ItemRepository_Get_Call) Return(_a0 *model.Item, _a1 error) *ItemRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Item, error)) *ItemRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: _a0
func (_m *ItemRepository) List(_a0 context.Context) ([]*model.Item, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Item, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Item); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ItemRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ItemRepository_Expecter) List(_a0 interface{}) *ItemRepository_List_Call {
	return &ItemRepository_List_Call{Call: _e.mock.On("List", _a0)}
}

func (_c *ItemRepository_List_Call) Run(run func(_a0 context.Context)) *ItemRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ItemRepository_List_Call) Return(_a0 []*model.Item, _a1 error) *ItemRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_List_Call) RunAndReturn(run func(context.Context) ([]*model.Item, error)) *ItemRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemRepository creates a new instance of ItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepository {
	mock := &ItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
