// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sborsh1kmusora/micro/order/internal/model"
)

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// ListItems provides a mock function with given fields: _a0, _a1
func (_m *InventoryClient) ListItems(_a0 context.Context, _a1 []string) ([]*model.Item, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []*model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Item, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Item); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryClient_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type InventoryClient_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []string
func (_e *InventoryClient_Expecter) ListItems(_a0 interface{}, _a1 interface{}) *InventoryClient_ListItems_Call {
	return &InventoryClient_ListItems_Call{Call: _e.mock.On("ListItems", _a0, _a1)}
}

func (_c *InventoryClient_ListItems_Call) Run(run func(_a0 context.Context, _a1 []string)) *InventoryClient_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *InventoryClient_ListItems_Call) Return(_a0 []*model.Item, _a1 error) *InventoryClient_ListItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryClient_ListItems_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Item, error)) *InventoryClient_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
