with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True
disable-version-string: True

packages:
  github.com/sborsh1kmusora/micro/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/sborsh1kmusora/micro/inventory/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/sborsh1kmusora/micro/order/internal/service:
    config:
      include-regex: ".*Service"

  github.com/sborsh1kmusora/micro/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/sborsh1kmusora/micro/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  github.com/sborsh1kmusora/micro/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/sborsh1kmusora/micro/payment/internal/repository:
    config:
      include-regex: ".*Repository"