// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sborsh1kmusora/micro/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ItemService is an autogenerated mock type for the ItemService type
type ItemService struct {
	mock.Mock
}

type ItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemService) EXPECT() *ItemService_Expecter {
	return &ItemService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ItemService) Create(_a0 context.Context, _a1 *model.ItemInfo) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ItemInfo) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ItemInfo) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ItemInfo) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ItemService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *model.ItemInfo
func (_e *ItemService_Expecter) Create(_a0 interface{}, _a1 interface{}) *ItemService_Create_Call {
	return &ItemService_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *ItemService_Create_Call) Run(run func(_a0 context.Context, _a1 *model.ItemInfo)) *ItemService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.ItemInfo))
	})
	return _c
}

func (_c *ItemService_Create_Call) Return(_a0 string, _a1 error) *ItemService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_Create_Call) RunAndReturn(run func(context.Context, *model.ItemInfo) (string, error)) *ItemService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *ItemService) Get(_a0 context.Context, _a1 string) (*model.Item, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Item, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Item); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ItemService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ItemService_Expecter) Get(_a0 interface{}, _a1 interface{}) *ItemService_Get_Call {
	return &ItemService_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *ItemService_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *ItemService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ItemService_Get_Call) Return(_a0 *model.Item, _a1 error) *ItemService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Item, error)) *ItemService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: _a0, _a1
func (_m *ItemService) List(_a0 context.Context, _a1 []string) ([]*model.Item, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Item, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Item); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ItemService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []string
func (_e *ItemService_Expecter) List(_a0 interface{}, _a1 interface{}) *ItemService_List_Call {
	return &ItemService_List_Call{Call: _e.mock.On("List", _a0, _a1)}
}

func (_c *ItemService_List_Call) Run(run func(_a0 context.Context, _a1 []string)) *ItemService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *ItemService_List_Call) Return(_a0 []*model.Item, _a1 error) *ItemService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_List_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Item, error)) *ItemService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemService creates a new instance of ItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemService {
	mock := &ItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
